version: '3.8'

services:
  spring-app:
    build: .
    container_name: libreria
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    # Opcional: si necesitas base de datos
    depends_on:
      - mysql
  
  # Opcional: si tu app usa MySQL
  mysql:
    image: mysql:8
    container_name: libreria-mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: libreria_db

      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: