server.port=${PORT:8080}
server.address=0.0.0.0
#spring.datasource.url=jdbc:mysql://database-1-instance-1.cjc4eueoljbb.us-east-1.rds.amazonaws.com:3306/mydb?serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://newfarmaserver.mysql.database.azure.com:3306/mydb?serverTimezone=UTC
spring.application.name=app_newfarma

#PARA USAR LA BD ALOJADA EN DOCKER
#spring.datasource.url=jdbc:mysql://newfarmabd:3306/mydbfull
#spring.datasource.username=${DB_USER_NAME}
#spring.datasource.password=${DB_PASSWORD}


#PARA USAR LA BD ALOJADA EN RAILWAY
spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:57712/mydbfull
spring.datasource.username=root
spring.datasource.password=NUqnMFYOEhbjXTCFDGMCvlwVFcXesOAr

# Logging configuration
logging.level.root=INFO
logging.level.org.springframework.boot=DEBUG
logging.level.org.springframework.web=DEBUG
logging.file.path=
logging.file.name=

# Console logging pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n



#PARA USAR LA BD EN XAMM LOCAL
#spring.datasource.url=jdbc:mysql://localhost:3306/mydbfull
#spring.datasource.username=root
#spring.datasource.password=


spring.jpa.show-sql=true
logging.level.org.springframework.jdbc.core=DEBUG
spring.sql.init.mode=always
secret-key=${SECRET_KEY}
jwt.expiration=${EXPIRATION}
refresh.expiration=${REFRESH_EXPIRATION}
